In [1]:
print('Hi RAA')

Hi RAA


In [2]:
# https://www.kaggle.com/ dataset
print('https://www.kaggle.com/')

https://www.kaggle.com/


In [3]:
import numpy as np
import pandas as pd

In [4]:
np

<module 'numpy' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [5]:
dataset=pd.read_csv('dataset\DiabetesHealthIndicatorsDataset\data.csv')

In [6]:
dataset

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                   0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                   0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                   0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                   0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                   0.0     1.0       1.0        1.0  24.0     0.0     0.0   
...                 ...     ...       ...        ...   ...     ...     ...   
253675              0.0     1.0       1.0        1.0  45.0     0.0     0.0   
253676              1.0     1.0       1.0        1.0  18.0     0.0     0.0   
253677              0.0     0.0       0.0        1.0  28.0     0.0     0.0   
253678              0.0     1.0       0.0        1.0  23.0     0.0     0.0   
253679              1.0     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                        0.0           0.0     0.0  ...            1.0   
1                        0.0           1.0     0.0  ...            0.0   
2                        0.0           0.0     1.0  ...            1.0   
3                        0.0           1.0     1.0  ...            1.0   
4                        0.0           1.0     1.0  ...            1.0   
...                      ...           ...     ...  ...            ...   
253675                   0.0           0.0     1.0  ...            1.0   
253676                   0.0           0.0     0.0  ...            1.0   
253677                   0.0           1.0     1.0  ...            1.0   
253678                   0.0           0.0     1.0  ...            1.0   
253679                   1.0           1.0     1.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
0               0.0      5.0      18.0      15.0       1.0  0.0   9.0   
1               1.0      3.0       0.0       0.0       0.0  0.0   7.0   
2               1.0      5.0      30.0      30.0       1.0  0.0   9.0   
3               0.0      2.0       0.0       0.0       0.0  0.0  11.0   
4               0.0      2.0       3.0       0.0       0.0  0.0  11.0   
...             ...      ...       ...       ...       ...  ...   ...   
253675          0.0      3.0       0.0       5.0       0.0  1.0   5.0   
253676          0.0      4.0       0.0       0.0       1.0  0.0  11.0   
253677          0.0      1.0       0.0       0.0       0.0  0.0   2.0   
253678          0.0      3.0       0.0       0.0       0.0  1.0   7.0   
253679          0.0      2.0       0.0       0.0       0.0  0.0   9.0   

        Education  Income  
0             4.0     3.0  
1             6.0     1.0  
2             4.0     8.0  
3             3.0     6.0  
4             5.0     4.0  
...           ...     ...  
253675        6.0     7.0  
253676        2.0     4.0  
253677        5.0     2.0  
253678        5.0     1.0  
253679        6.0     2.0  

[253680 rows x 22 columns]

In [8]:
dataset[0:10]

Diabetes_binary  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0              0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1              0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2              0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3              0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4              0.0     1.0       1.0        1.0  24.0     0.0     0.0   
5              0.0     1.0       1.0        1.0  25.0     1.0     0.0   
6              0.0     1.0       0.0        1.0  30.0     1.0     0.0   
7              0.0     1.0       1.0        1.0  25.0     1.0     0.0   
8              1.0     1.0       1.0        1.0  30.0     1.0     0.0   
9              0.0     0.0       0.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   
5                   0.0           1.0     1.0  ...            1.0   
6                   0.0           0.0     0.0  ...            1.0   
7                   0.0           1.0     0.0  ...            1.0   
8                   1.0           0.0     1.0  ...            1.0   
9                   0.0           0.0     0.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   
5          0.0      2.0       0.0       2.0       0.0  1.0  10.0        6.0   
6          0.0      3.0       0.0      14.0       0.0  0.0   9.0        6.0   
7          0.0      3.0       0.0       0.0       1.0  0.0  11.0        4.0   
8          0.0      5.0      30.0      30.0       1.0  0.0   9.0        5.0   
9          0.0      2.0       0.0       0.0       0.0  1.0   8.0        4.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  
5     8.0  
6     7.0  
7     4.0  
8     1.0  
9     3.0  

[10 rows x 22 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [12]:
Y = dataset.iloc[:, 1:].values

In [13]:
Y

array([[1., 1., 1., ..., 9., 4., 3.],
       [0., 0., 0., ..., 7., 6., 1.],
       [1., 1., 1., ..., 9., 4., 8.],
       ...,
       [0., 0., 1., ..., 2., 5., 2.],
       [1., 0., 1., ..., 7., 5., 1.],
       [1., 1., 1., ..., 9., 6., 2.]])

In [11]:
Y

array([[0., 1., 1., ..., 0., 9., 4.],
       [0., 0., 0., ..., 0., 7., 6.],
       [0., 1., 1., ..., 0., 9., 4.],
       ...,
       [0., 0., 0., ..., 0., 2., 5.],
       [0., 1., 0., ..., 1., 7., 5.],
       [1., 1., 1., ..., 0., 9., 6.]])

In [14]:
X = dataset.iloc[:, 1:].values

In [15]:
X

array([[1., 1., 1., ..., 9., 4., 3.],
       [0., 0., 0., ..., 7., 6., 1.],
       [1., 1., 1., ..., 9., 4., 8.],
       ...,
       [0., 0., 1., ..., 2., 5., 2.],
       [1., 0., 1., ..., 7., 5., 1.],
       [1., 1., 1., ..., 9., 6., 2.]])

In [22]:
y = dataset.iloc[:, 0:1].values

In [21]:
Y

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [27]:
X_train

array([[ 0.,  0.,  1., ...,  7.,  5.,  7.],
       [ 0.,  0.,  1., ...,  3.,  5.,  6.],
       [ 0.,  0.,  1., ...,  6.,  6.,  8.],
       ...,
       [ 1.,  1.,  1., ..., 13.,  4.,  6.],
       [ 1.,  1.,  1., ..., 12.,  5.,  7.],
       [ 0.,  0.,  1., ..., 12.,  5.,  7.]])

In [28]:
y_train

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [1.]])

In [17]:
Y

array([0., 0., 0., ..., 0., 0., 1.])

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc_x=StandardScaler()

In [33]:
sc_x

StandardScaler()

In [35]:
x_train=sc_x.fit_transform(X_train)

In [36]:
x_train

array([[-0.86694055, -0.85824396,  0.19721838, ..., -0.33689486,
        -0.05272846,  0.45658877],
       [-0.86694055, -0.85824396,  0.19721838, ..., -1.64678048,
        -0.05272846, -0.02653888],
       [-0.86694055, -0.85824396,  0.19721838, ..., -0.66436626,
         0.96282864,  0.93971643],
       ...,
       [ 1.15348163,  1.16516987,  0.19721838, ...,  1.62793357,
        -1.06828557, -0.02653888],
       [ 1.15348163,  1.16516987,  0.19721838, ...,  1.30046217,
        -0.05272846,  0.45658877],
       [-0.86694055, -0.85824396,  0.19721838, ...,  1.30046217,
        -0.05272846,  0.45658877]])

In [37]:
x_test=sc_x.fit_transform(X_test)

In [38]:
x_test

array([[-0.86616481, -0.85793234,  0.19573046, ..., -1.3236875 ,
        -0.0449299 , -2.43202028],
       [-0.86616481, -0.85793234,  0.19573046, ...,  0.96671778,
        -1.05492688,  0.93933116],
       [-0.86616481, -0.85793234,  0.19573046, ...,  0.31231627,
        -1.05492688,  0.45770952],
       ...,
       [-0.86616481, -0.85793234,  0.19573046, ...,  0.31231627,
         0.96506709,  0.93933116],
       [ 1.15451469, -0.85793234,  0.19573046, ..., -0.34208524,
         0.96506709, -2.43202028],
       [ 1.15451469,  1.16559308,  0.19573046, ...,  0.63951702,
        -1.05492688, -2.43202028]])